sonar.projectKey=bookstore:user:spa
sonar.projectName=Bookstore User SPA

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/reports/**,.scannerwork/**,**/dist/**,**/coverage/**,**/environments/**,src/assets/**,**/docs/**,**/test-results/**,**/playwright-report/**,**/.windsurf/**,**/.vscode/**,**/.angular/**

sonar.sourceEncoding=UTF-8
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Report export settings
sonar.export.path=reports/sonar
